[alacritty]
src.git = "https://github.com/catppuccin/alacritty.git"
fetch.github = "catppuccin/alacritty"

[bat]
src.git = "https://github.com/catppuccin/bat.git"
fetch.github = "catppuccin/bat"

[bottom]
src.git = "https://github.com/catppuccin/bottom.git"
fetch.github = "catppuccin/bottom"

[btop]
src.git = "https://github.com/catppuccin/btop.git"
fetch.github = "catppuccin/btop"

[fish]
src.git = "https://github.com/catppuccin/fish.git"
fetch.github = "catppuccin/fish"

[glamour]
src.git = "https://github.com/catppuccin/glamour.git"
fetch.github = "catppuccin/glamour"

[grub]
src.git = "https://github.com/catppuccin/grub.git"
fetch.github = "catppuccin/grub"

[gtk]
src.git = "https://github.com/catppuccin/gtk.git"
fetch.github = "catppuccin/gtk"

[helix]
src.git = "https://github.com/catppuccin/helix.git"
fetch.github = "catppuccin/helix"

[hyprland]
src.git = "https://github.com/catppuccin/hyprland.git"
fetch.github = "catppuccin/hyprland"

[kitty]
src.git = "https://github.com/catppuccin/kitty.git"
fetch.github = "catppuccin/kitty"

[lazygit]
src.git = "https://github.com/catppuccin/lazygit.git"
fetch.github = "catppuccin/lazygit"

[mako]
src.git = "https://github.com/catppuccin/mako.git"
fetch.github = "catppuccin/mako"

[micro]
src.git = "https://github.com/catppuccin/micro.git"
fetch.github = "catppuccin/micro"

[neovim]
src.git = "https://github.com/catppuccin/nvim.git"
fetch.github = "catppuccin/nvim"

[polybar]
src.git = "https://github.com/catppuccin/polybar.git"
fetch.github = "catppuccin/polybar"

[starship]
src.git = "https://github.com/catppuccin/starship.git"
fetch.github = "catppuccin/starship"

[sway]
src.git = "https://github.com/catppuccin/sway.git"
fetch.github = "catppuccin/sway"

[tmux]
src.git = "https://github.com/catppuccin/tmux.git"
fetch.github = "catppuccin/tmux"

[zathura]
src.git = "https://github.com/catppuccin/zathura.git"
fetch.github = "catppuccin/zathura"
