[alacritty]
src.git = "https://github.com/catppuccin/alacritty.git"
fetch.github = "catppuccin/alacritty"

[bat]
src.git = "https://github.com/catppuccin/bat.git"
fetch.github = "catppuccin/bat"

[bottom]
src.git = "https://github.com/catppuccin/bottom.git"
fetch.github = "catppuccin/bottom"

[btop]
src.git = "https://github.com/catppuccin/btop.git"
fetch.github = "catppuccin/btop"

[cava]
src.git = "https://github.com/catppuccin/cava.git"
fetch.github = "catppuccin/cava"

[delta]
src.git = "https://github.com/catppuccin/delta.git"
fetch.github = "catppuccin/delta"

[dunst]
src.git = "https://github.com/catppuccin/dunst.git"
fetch.github = "catppuccin/dunst"

[fcitx5]
src.git = "https://github.com/catppuccin/fcitx5.git"
fetch.github = "catppuccin/fcitx5"

[fish]
src.git = "https://github.com/catppuccin/fish.git"
fetch.github = "catppuccin/fish"

[foot]
src.git = "https://github.com/catppuccin/foot.git"
fetch.github = "catppuccin/foot"

[gh-dash]
src.git = "https://github.com/catppuccin/gh-dash.git"
fetch.github = "catppuccin/gh-dash"

[gitui]
src.git = "https://github.com/catppuccin/gitui.git"
fetch.github = "catppuccin/gitui"

[glamour]
src.git = "https://github.com/catppuccin/glamour.git"
fetch.github = "catppuccin/glamour"

[grub]
src.git = "https://github.com/catppuccin/grub.git"
fetch.github = "catppuccin/grub"

[helix]
src.git = "https://github.com/catppuccin/helix.git"
fetch.github = "catppuccin/helix"

[hyprland]
src.git = "https://github.com/catppuccin/hyprland.git"
fetch.github = "catppuccin/hyprland"

[imv]
src.git = "https://github.com/catppuccin/imv.git"
fetch.github = "catppuccin/imv"

[k9s]
src.git = "https://github.com/catppuccin/k9s.git"
fetch.github = "catppuccin/k9s"

[kitty]
src.git = "https://github.com/catppuccin/kitty.git"
fetch.github = "catppuccin/kitty"

[lazygit]
src.git = "https://github.com/catppuccin/lazygit.git"
fetch.github = "catppuccin/lazygit"

[mako]
src.git = "https://github.com/catppuccin/mako.git"
fetch.github = "catppuccin/mako"

[micro]
src.git = "https://github.com/catppuccin/micro.git"
fetch.github = "catppuccin/micro"

[mpv]
src.git = "https://github.com/catppuccin/mpv.git"
fetch.github = "catppuccin/mpv"

[neovim]
src.git = "https://github.com/catppuccin/nvim.git"
fetch.github = "catppuccin/nvim"

[palette]
src.git = "https://github.com/catppuccin/palette"
fetch.github = "catppuccin/palette"

[polybar]
src.git = "https://github.com/catppuccin/polybar.git"
fetch.github = "catppuccin/polybar"

[rio]
src.git = "https://github.com/catppuccin/rio.git"
fetch.github = "catppuccin/rio"

[rofi]
src.git = "https://github.com/catppuccin/rofi.git"
fetch.github = "catppuccin/rofi"

[starship]
src.git = "https://github.com/catppuccin/starship.git"
fetch.github = "catppuccin/starship"

[sway]
src.git = "https://github.com/catppuccin/sway.git"
fetch.github = "catppuccin/sway"

[swaylock]
src.git = "https://github.com/catppuccin/swaylock.git"
fetch.github = "catppuccin/swaylock"

[tmux]
src.git = "https://github.com/catppuccin/tmux.git"
fetch.github = "catppuccin/tmux"

[tofi]
src.git = "https://github.com/catppuccin/tofi.git"
fetch.github = "catppuccin/tofi"

[waybar]
src.git = "https://github.com/catppuccin/waybar.git"
fetch.github = "catppuccin/waybar"

[yazi]
src.git = "https://github.com/catppuccin/yazi.git"
fetch.github = "catppuccin/yazi"

[zathura]
src.git = "https://github.com/catppuccin/zathura.git"
fetch.github = "catppuccin/zathura"
